### ISSUE TITLE
naive_gemm.cu文件中的最外层循环i的范围

### ISSUE THREAD

**Issue by Shunli-Wang** [Pzzzzz5142/NLP-Inference-MM#9]
这个文件里面的第24行，i的范围是不是应该为0...K？而不是0...8？

` 
for (int i = 0; i < 8; i++)
`

[naive_gemm.cu](https://github.com/AyakaGEMM/Hands-on-GEMM/blob/main/src/cuda/naive_gemm.cu)

**Comment by Pzzzzz5142** [comment]
我觉得你说的对（

**Comment by Pzzzzz5142** [comment]
另外 `float aa[64]` 也没有初始化，这坨应该当时瞎写的。
